### ISSUE TITLE
# TODO & UPDATE

### ISSUE THREAD

**Issue by yuanlinm** [yuanlinm/FORESTPLOT.PAC#1]
- [x] 右边数据纵标目显示似乎依然是左对齐，应修正为居中对齐
- [x] 应该添加自动对数值型列的，含NA数据的不展示“NA”处理功能
- [x] 考虑添加缩进向量控制首列行缩进
- [x] 应该添加纵标目下边线的垂直位置调整参数

---

**Comment by yuanlinm** [comment]
- [ ] 修正了全局图形的显示宽度bug，现在能够正确显示X轴的expand了，使用table_scale和first_col_mv参数可以适当调整表格层的间隙宽度
- [ ] 修复了不提供right_side_data时的报错bug
- [ ] 对于first_col_mv的宽容度默认提供最大-0.5的移动限制，需要更多的左移时请配合更大尺寸的图形以及table_scale调整

**Comment by yuanlinm** [comment]
- [ ] 调整默认的字体为sans，修复了部分环境可能不支持Arial字体产生的报错

**Comment by yuanlinm** [comment]
细节参数后续再添加，代码已重构。
